{% set name = "yaqd-pmc" %}
{% set version = "2022.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6012deb214a321019a37580bdf0ee883c7e9fc50bfe7035270f3943e242c9d6c

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-pmc = yaqd_pmc._pmc:PmcMotor.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - flit
    - yaqd-core >=2020.10.1
  run:
    - python >=3.7
    - yaqd-core >=2020.10.1

test:
  imports:
    - yaqd_pmc
  commands:
    - pip check
    - yaqd-pmc --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq daemons for Precision MicroControl Corp. hardware
  dev_url: https://gitlab.com/yaq/yaqd-pmc
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
